DROP TABLE IF EXISTS "Media";
DROP TABLE IF EXISTS "SongArtist";
DROP TABLE IF EXISTS "AlbumSong";
DROP TABLE IF EXISTS "MediaType";
DROP TABLE IF EXISTS "Song";
DROP TABLE IF EXISTS "Artist";
DROP TABLE IF EXISTS "Album";

CREATE TABLE IF NOT EXISTS "Artist"
(
"Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"Name" VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Album"
(
"Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"Title" VARCHAR(200) NOT NULL,
"ReleaseDate" DATE
);


CREATE TABLE IF NOT EXISTS "Song"
(
"Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"Title" VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS "SongArtist"
(
"SongId" INTEGER NOT NULL,
"ArtistId" INTEGER NOT NULL,
"IsMainArtist" BOOLEAN NOT NULL DEFAULT TRUE,

CONSTRAINT PK_SongArtist
PRIMARY KEY ("SongId", "ArtistId"),

CONSTRAINT FK_SongArtist_Song
FOREIGN KEY ("SongId")
REFERENCES "Song"("Id")
ON DELETE CASCADE,

CONSTRAINT FK_SongArtist_Artist
FOREIGN KEY ("ArtistId")
REFERENCES "Artist"("Id")
ON DELETE CASCADE
);

CREATE UNIQUE INDEX UX_SongArtist_OneMainArtist
ON "SongArtist" ("SongId")
WHERE "IsMainArtist" = TRUE;

CREATE TABLE IF NOT EXISTS "AlbumSong"
(
"AlbumId" INTEGER NOT NULL,
"SongId" INTEGER NOT NULL,

CONSTRAINT PK_AlbumSong
PRIMARY KEY ("AlbumId", "SongId"),

CONSTRAINT FK_AlbumSong_Album
FOREIGN KEY ("AlbumId")
REFERENCES "Album"("Id")
ON DELETE CASCADE,

CONSTRAINT FK_AlbumSong_Song
FOREIGN KEY ("SongId")
REFERENCES "Song"("Id")
ON DELETE CASCADE


);

CREATE TABLE IF NOT EXISTS "MediaType"
(
"Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"Name" VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "Media"
(
"Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"ExternalId" VARCHAR(255) NOT NULL,
"SongId" INTEGER NOT NULL,
"MediaTypeId" INTEGER NOT NULL,

CONSTRAINT FK_Media_Song
FOREIGN KEY ("SongId")
REFERENCES "Song"("Id")
ON DELETE CASCADE,

CONSTRAINT FK_Media_MediaType
FOREIGN KEY ("MediaTypeId")
REFERENCES "MediaType"("Id")
);


