--uncomment to reset db tables
--DROP TABLE IF EXISTS "Media";
--DROP TABLE IF EXISTS "SongArtist";
--DROP TABLE IF EXISTS "AlbumSong";
--DROP TABLE IF EXISTS "MediaType";
--DROP TABLE IF EXISTS "Song";
--DROP TABLE IF EXISTS "Artist";
--DROP TABLE IF EXISTS "Album";
--DROP TABLE IF EXISTS "User";

CREATE TABLE IF NOT EXISTS "Artist"
(
"Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"Name" VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Album"
(
"Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"Title" VARCHAR(200) NOT NULL,
"ReleaseDate" DATE
);


CREATE TABLE IF NOT EXISTS "Song"
(
"Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"Title" VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS "SongArtist"
(
"SongId" INTEGER NOT NULL,
"ArtistId" INTEGER NOT NULL,
"IsMainArtist" BOOLEAN NOT NULL DEFAULT TRUE,

CONSTRAINT PK_SongArtist
PRIMARY KEY ("SongId", "ArtistId"),

CONSTRAINT FK_SongArtist_Song
FOREIGN KEY ("SongId")
REFERENCES "Song"("Id")
ON DELETE CASCADE,

CONSTRAINT FK_SongArtist_Artist
FOREIGN KEY ("ArtistId")
REFERENCES "Artist"("Id")
ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS UX_SongArtist_OneMainArtist
ON "SongArtist" ("SongId")
WHERE "IsMainArtist" = TRUE;

CREATE TABLE IF NOT EXISTS "AlbumSong"
(
"AlbumId" INTEGER NOT NULL,
"SongId" INTEGER NOT NULL,

CONSTRAINT PK_AlbumSong
PRIMARY KEY ("AlbumId", "SongId"),

CONSTRAINT FK_AlbumSong_Album
FOREIGN KEY ("AlbumId")
REFERENCES "Album"("Id")
ON DELETE CASCADE,

CONSTRAINT FK_AlbumSong_Song
FOREIGN KEY ("SongId")
REFERENCES "Song"("Id")
ON DELETE CASCADE


);

CREATE TABLE IF NOT EXISTS "MediaType"
(
"Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"Name" VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "Media"
(
"Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"ExternalId" VARCHAR(255) NOT NULL,
"SongId" INTEGER NOT NULL,
"MediaTypeId" INTEGER NOT NULL,

CONSTRAINT FK_Media_Song
FOREIGN KEY ("SongId")
REFERENCES "Song"("Id")
ON DELETE CASCADE,

CONSTRAINT FK_Media_MediaType
FOREIGN KEY ("MediaTypeId")
REFERENCES "MediaType"("Id")
);

CREATE TABLE IF NOT EXISTS "User"
(
    "Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Username" VARCHAR(100) NOT NULL UNIQUE,
    "Password" VARCHAR(255) NOT NULL,
    "Role" VARCHAR(20) NOT NULL DEFAULT 'User',

    CONSTRAINT CK_User_Role
    CHECK ("Role" IN ('User', 'Admin'))
);
CREATE OR REPLACE PROCEDURE CreateUser(
    p_username VARCHAR(100),
    p_password VARCHAR(255),
    p_role VARCHAR(20)
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_username IS NULL OR TRIM(p_username) = '' THEN
        RAISE EXCEPTION 'Username cannot be empty.';
    END IF;

    IF p_password IS NULL OR TRIM(p_password) = '' THEN
        RAISE EXCEPTION 'Password cannot be empty.';
    END IF;

    IF p_role NOT IN ('User', 'Admin') THEN
        RAISE EXCEPTION 'Invalid role.';
    END IF;

    INSERT INTO "User" ("Username", "Password", "Role")
    VALUES (p_username, p_password, p_role);

EXCEPTION
    WHEN unique_violation THEN
        RAISE EXCEPTION 'Username already exists.';
END;
$$;

